name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      UID: 1001
      # NOTE: https://typicode.github.io/husky/how-to.html#ci-server-and-docker
      HUSKY: 0

    steps:
      - uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

      - name: Prepare .env
        run: cp .env.example .env.production

      - name: Build the Docker image
        run: make prod-docker-build
